name: Build App

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      output_directory:
        type: string
        default: .
      cache_file:
        type: string
        default: "requirements.txt"
      make_target_prefix:
        type: string
        default: ""

env:
  AR_REPO: ${{ inputs.repo }}
  AR_REQS_REPO: ${{ vars.CODECOV_UMBRELLA_REQS_IMAGE || 'codecov/umbrella-reqs-fallback' }}

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: 'recursive'
      - id: "auth"
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2.1.2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.CODECOV_GCP_WIDP }}
          service_account: ${{ secrets.CODECOV_GCP_WIDSA }}

      - name: Docker configuration
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

      - name: Cache Requirements
        id: cache-requirements
        uses: actions/cache@v4
        env:
          # Forks can't access the variable containing our actual image repository. We want to
          # use a separate cache to make sure they don't interfere with reqs images being pushed.
          cache-name: ${{ !github.event.pull_request.repo.fork && 'umbrella-requirements' || 'umbrella-requirements-fork' }}
        with:
          path: |
            ./requirements.tar
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.cache-name }}-${{ hashFiles('uv.lock') }}-${{ hashFiles('docker/Dockerfile.requirements') }}-${{ hashFiles('libs/shared/**') }}

      - name: Cache App
        id: cache-app
        uses: actions/cache@v4
        env:
          cache-name: ${{ inputs.repo }}-app
        with:
          path: |
            ${{ inputs.output_directory }}/app.tar
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}

      - name: Load requirements from cache
        if: ${{ steps.cache-requirements.outputs.cache-hit == 'true' }}
        run: |
          make load.requirements

      # This shouldn't happen; the _build-requirements.yml job should have run.
      - name: Build/pull requirements
        if: ${{ steps.cache-requirements.outputs.cache-hit != 'true' }}
        run: |
          echo "Warning: requirements image not in cache, building a new one"
          make build.requirements
          make save.requirements

      - name: Build app
        run: |
          make ${{ inputs.make_target_prefix }}build.app
          make ${{ inputs.make_target_prefix }}save.app

