name: Push to Stage

on:
  push:
    tags:
      - stage-*
    branches:
      - staging
  pull_request:
  merge_group:

permissions:
  contents: "read"
  id-token: "write"
  issues: "write"
  pull-requests: "write"

jobs:

    worker:
        name: Push Staging Image (Worker)
        if: ${{ github.repository_owner == 'codecov' && github.event_name == 'push' && github.event.ref == 'refs/heads/staging' }}
        uses: ./.github/workflows/_push-env.yml
        secrets: inherit
        with:
          environment: staging
          repo: ${{ vars.CODECOV_WORKER_IMAGE_V2 || vars.CODECOV_WORKER_IMAGE_V2_SELF_HOSTED || 'codecov/self-hosted-worker' }}
          output_directory: apps/worker
          sentry_project: worker
          make_target_prefix: worker.

    trigger-worker-deploy:
        name: Trigger codecov-worker deployment
        needs: [worker]
        if: ${{ !cancelled() && github.event_name == 'push' }}
        uses: ./.github/workflows/trigger-worker-deploy.yml

    api:
        name: Push Staging Image (API)
        if: ${{ github.repository_owner == 'codecov' && github.event_name == 'push' && github.event.ref == 'refs/heads/staging' }}
        uses: ./.github/workflows/_push-env.yml
        secrets: inherit
        with:
            environment: staging
            repo: ${{ vars.CODECOV_API_IMAGE_V2 || vars.CODECOV_API_IMAGE_V2_SELF_HOSTED || 'codecov/self-hosted-api' }}
            output_directory: apps/codecov-api
            sentry_project: api
            make_target_prefix: api.
    
    trigger-api-deploy:
        name: Trigger codecov-api deployment
        needs: [api]
        if: ${{ !cancelled() && github.event_name == 'push' }}
        uses: ./.github/workflows/trigger-api-deploy.yml